package com.saatco.murshadik.Helpers;

import com.saatco.murshadik.model.City;

import java.util.ArrayList;

public class CountryHelper {

    public static  ArrayList<City> getCountries (){

        ArrayList<City> country = new ArrayList<>();

        country.add(new City("المملكة العربية السعودية","+966","SA"));
        country.add(new City("الامارات العربية المتحدة","+971","AE"));
        country.add(new City("عمان","+968","OM"));
        country.add(new City("الكويت","+965","KW"));
        country.add(new City("البحرين","+973","BH"));
        country.add(new City("قطر","+974","QA"));
        country.add(new City("العراق","+964","IQ"));
        country.add(new City("اليمن","+967","YE"));
        country.add(new City("تركيا","+90","TR"));
        country.add(new City("الأردن","+962","JO"));
        country.add(new City("سوريا","+963","SY"));
        country.add(new City("فلسطين","+970","PS"));
        country.add(new City("لبنان","+961","LB"));
        country.add(new City("مصر","+20","EG"));
        country.add(new City("الجزائر","+213","DZ"));
        country.add(new City("السودان","+249","SD"));
        country.add(new City("تونس","+216","TN"));
        country.add(new City("المغرب","+212","MA"));
        country.add(new City("موريتانيا","+222","MR"));
        country.add(new City("ليبيا","+218","LY"));
        country.add(new City("جيبوتي","+253","DJ"));
        country.add(new City("الصومال","+252","SO"));
        country.add(new City("اريتريا","+291","ER"));



       /* country.add(new City("أفغانستان","+93","AF"));
        country.add(new City("أنتيجوا وبربودا","+1","AG"));
        country.add(new City("أنجويلا","+1","AI"));
        country.add(new City("أرمينيا","+374","AM"));
        country.add(new City("أنجولا","+244","AO"));
        country.add(new City("القطب الجنوبي","+672","AQ"));
        country.add(new City("الأرجنتين","+54","AR"));
        country.add(new City("النمسا","+43","AS"));
        country.add(new City("أستراليا","+61","AU"));
        country.add(new City("آروبا","+297","AW"));
        country.add(new City("جزر أولان","+358","AX"));
        country.add(new City("أذربيجان","+994","AZ"));
        country.add(new City("البوسنة والهرسك","+387","BA"));
        country.add(new City("بربادوس","+1","BB"));
        country.add(new City("بنجلاديش","+880","BD"));
        country.add(new City("بلجيكا","+32","BE"));
        country.add(new City("بوركينا فاسو","+226","BF"));
        country.add(new City("بلغاريا","+359","BG"));
        country.add(new City("البحرين","+973","BH"));
        country.add(new City("بوروندي","+257","BI"));
        country.add(new City("بنين","+229","BJ"));
        country.add(new City("سان بارتيلمي","+590","BL"));
        country.add(new City("برمودا","+1","BM"));
        country.add(new City("بروناي","+673","BN"));
        country.add(new City("بونير","+591","BO"));
        country.add(new City("البرازيل","+55","BR"));
        country.add(new City("الباهاما","+1","BS"));
        country.add(new City("بوتان","+975","BT"));
        country.add(new City("جزيرة بوفيه","+47","BT"));
        country.add(new City("بتسوانا","+267","BW"));
        country.add(new City("روسيا البيضاء","+375","BY"));
        country.add(new City("بليز","+501","BZ"));
        country.add(new City("كندا","+1","CA"));
        country.add(new City("جزر كوكوس","+61","CC"));
        country.add(new City("جمهورية الكونغو الديمقراطية","+243","CD"));
        country.add(new City("جمهورية افريقيا الوسطى","+236","CF"));
        country.add(new City("الكونغو - برازافيل","+242","CG"));
        country.add(new City("سويسرا","+41","CH"));
        country.add(new City("ساحل العاج","+225","CI"));
        country.add(new City("جزر كوك","+682","CK"));
        country.add(new City("شيلي","+56","CL"));
        country.add(new City("الكاميرون","+237","CM"));
        country.add(new City("الصين","+86","CN"));
        country.add(new City("كولومبيا","+57","CO"));
        country.add(new City("كوستاريكا","+506","CR"));
        country.add(new City("كوبا","+53","CU"));
        country.add(new City("الرأس الأخضر","+238","CV"));
        country.add(new City("كوراساو","+599","CW"));
        country.add(new City("جزيرة الكريسماس","+61","CX"));
        country.add(new City("قبرص","+357","CY"));
        country.add(new City("جمهورية التشيك","+420","CZ"));
        country.add(new City("ألمانيا","+49","DE"));
        country.add(new City("جيبوتي","+253","DJ"));
        country.add(new City("الدانمرك","+45","DK"));
        country.add(new City("دومينيكا","+1","DM"));
        country.add(new City("جمهورية الدومينيك","+1","DO"));
        country.add(new City("الجزائر","+213","DZ"));
        country.add(new City("الاكوادور","+593","EC"));
        country.add(new City("استونيا","+372","EE"));
        country.add(new City("مصر","+20","EG"));
        country.add(new City("الصحراء الغربية","+212","EH"));
        country.add(new City("اريتريا","+291","ER"));
        country.add(new City("أسبانيا","+34","ES"));
        country.add(new City("اثيوبيا","+251","ET"));
        country.add(new City("فنلندا","+358","FI"));
        country.add(new City("فيجي","+679","FJ"));
        country.add(new City("جزر فوكلاند","+500","FK"));
        country.add(new City("ميكرونيزيا","+691","FM"));
        country.add(new City("جزر فارو","+298","FO"));
        country.add(new City("فرنسا","+33","FR"));
        country.add(new City("الجابون","+241","GA"));
        country.add(new City("المملكة المتحدة","+44","GB"));
        country.add(new City("جرينادا","+1","GD"));
        country.add(new City("جورجيا","+995","GE"));
        country.add(new City("غويانا","+594","GF"));
        country.add(new City("غيرنزي","+44","GG"));
        country.add(new City("غانا","+233","GH"));
        country.add(new City("جبل طارق","+350","GI"));
        country.add(new City("جرينلاند","+299","GL"));
        country.add(new City("غامبيا","+220","GM"));
        country.add(new City("غينيا","+224","GN"));
        country.add(new City("جوادلوب","+590","GP"));
        country.add(new City("غينيا الاستوائية","+240","GQ"));
        country.add(new City("اليونان","+30","GR"));
        country.add(new City("جورجيا الجنوبية وجزر ساندويتش الجنوبية","+500","GS"));
        country.add(new City("جواتيمالا","+502","GT"));
        country.add(new City("جوام","+1","GU"));
        country.add(new City("غينيا بيساو","+245","GW"));
        country.add(new City("غيانا","+595","GY"));
        country.add(new City("هونج كونج الصينية","+852","HK"));
        country.add(new City("هندوراس","+504","HN"));
        country.add(new City("كرواتيا","+385","HR"));
        country.add(new City("هايتي","+509","HT"));
        country.add(new City("المجر","+36","HU"));
        country.add(new City("اندونيسيا","+62","ID"));
        country.add(new City("أيرلندا","+353","IE"));
        country.add(new City("اسرائيل","+972","IL"));
        country.add(new City("جزيرة مان","+44","IM"));
        country.add(new City("الهند","+91","IN"));
        country.add(new City("المحيط الهندي البريطاني","+246","IO"));
        country.add(new City("العراق","+964","IQ"));
        country.add(new City("ايران","+98","IR"));
        country.add(new City("أيسلندا","+354","IS"));
        country.add(new City("ايطاليا","+39","IT"));
        country.add(new City("جيرسي","+44","JE"));
        country.add(new City("جامايكا","+1","JM"));
        country.add(new City("الأردن","+962","JO"));
        country.add(new City("اليابان","+81","JP"));
        country.add(new City("كينيا","+254","KE"));
        country.add(new City("قرغيزستان","+996","KG"));
        country.add(new City("كمبوديا","+855","KH"));
        country.add(new City("كيريباتي","+686","KI"));
        country.add(new City("جزر القمر","+269","KM"));
        country.add(new City("سانت كيتس ونيفيس","+1","KN"));
        country.add(new City("كوريا الشمالية","+850","KP"));
        country.add(new City("كوريا الجنوبية","+82","KR"));
        country.add(new City("جزر الكايمن","+345","KY"));
        country.add(new City("كازاخستان","+7","KZ"));
        country.add(new City("لاوس","+856","LA"));
        country.add(new City("لبنان","+961","LB"));
        country.add(new City("سانت لوسيا","+1","LC"));
        country.add(new City("ليختنشتاين","+423","LI"));
        country.add(new City("سريلانكا","+94","LK"));
        country.add(new City("ليبيريا","+231","LR"));
        country.add(new City("ليسوتو","+266","LS"));
        country.add(new City("ليتوانيا","+370","LT"));
        country.add(new City("لوكسمبورج","+352","LU"));
        country.add(new City("لاتفيا","+371","LV"));
        country.add(new City("ليبيا","+218","LY"));
        country.add(new City("المغرب","+212","MA"));
        country.add(new City("موناكو","+377","MC"));
        country.add(new City("مولدافيا","+373","MD"));
        country.add(new City("الجبل الأسود","+382","ME"));
        country.add(new City("سانت مارتين","+590","MF"));
        country.add(new City("مدغشقر","+261","MG"));
        country.add(new City("جزر المارشال","+692","MH"));
        country.add(new City("مقدونيا","+389","MK"));
        country.add(new City("مالي","+223","ML"));
        country.add(new City("ميانمار","+95","MM"));
        country.add(new City("منغوليا","+976","MN"));
        country.add(new City("ماكاو الصينية","+853","MO"));
        country.add(new City("جزر ماريانا الشمالية","+1","MP"));
        country.add(new City("مارتينيك","+596","MQ"));
        country.add(new City("موريتانيا","+222","MR"));
        country.add(new City("مونتسرات","+1","MS"));
        country.add(new City("مالطا","+356","MT"));
        country.add(new City("موريشيوس","+230","MU"));
        country.add(new City("جزر الملديف","+960","MV"));
        country.add(new City("ملاوي","+265","MW"));
        country.add(new City("المكسيك","+52","MX"));
        country.add(new City("ماليزيا","+60","MY"));
        country.add(new City("موزمبيق","+258","MZ"));
        country.add(new City("ناميبيا","+264","NA"));
        country.add(new City("كاليدونيا الجديدة","+687","NC"));
        country.add(new City("النيجر","+227","NE"));
        country.add(new City("جزيرة نورفوك","+672","NF"));
        country.add(new City("نيجيريا","+234","NG"));
        country.add(new City("نيكاراجوا","+505","NI"));
        country.add(new City("هولندا","+31","NL"));
        country.add(new City("النرويج","+47","NO"));
        country.add(new City("نيبال","+977","NP"));
        country.add(new City("نورو","+674","NR"));
        country.add(new City("نيوي","+683","NU"));
        country.add(new City("نيوزيلاندا","+64","NZ"));
        country.add(new City("بنما","+507","PA"));
        country.add(new City("بيرو","+51","PE"));
        country.add(new City("بولينيزيا الفرنسية","+689","PF"));
        country.add(new City("بابوا غينيا الجديدة","+675","PG"));
        country.add(new City("الفيلبين","+63","PH"));
        country.add(new City("باكستان","+92","PK"));
        country.add(new City("بولندا","+48","PL"));
        country.add(new City("سانت بيير وميكولون","+508","PM"));
        country.add(new City("بتكايرن","+872","PN"));
        country.add(new City("بورتوريكو","+1","PR"));
        country.add(new City("فلسطين","+970","PS"));
        country.add(new City("البرتغال","+351","PT"));
        country.add(new City("بالاو","+680","PW"));
        country.add(new City("باراجواي","+595","PY"));
        country.add(new City("قطر","+974","QA"));
        country.add(new City("روينيون","+262","RE"));
        country.add(new City("رومانيا","+40","RO"));
        country.add(new City("صربيا","+381","RS"));
        country.add(new City("روسيا","+7","RU"));
        country.add(new City("رواندا","+250","RW"));
        country.add(new City("جزر سليمان","+677","SB"));
        country.add(new City("سيشل","+248","SC"));
        country.add(new City("السودان","+249","SD"));
        country.add(new City("السويد","+46","SE"));
        country.add(new City("سنغافورة","+65","SG"));
        country.add(new City("سانت هيلنا","+290","SH"));
        country.add(new City("سلوفينيا","+386","SH"));
        country.add(new City("سفالبارد وجان مايان","+47","SJ"));
        country.add(new City("سلوفاكيا","+421","SK"));
        country.add(new City("سيراليون","+232","SL"));
        country.add(new City("سان مارينو","+378","SM"));
        country.add(new City("السنغال","+221","SN"));
        country.add(new City("الصومال","+252","SO"));
        country.add(new City("سورينام","+597","SR"));
        country.add(new City("جنوب السودان","+211","SS"));
        country.add(new City("ساو تومي وبرينسيبي","+239","ST"));
        country.add(new City("السلفادور","+503","SV"));
        country.add(new City("سينت مارتن","+1","SX"));
        country.add(new City("سوريا","+963","SY"));
        country.add(new City("سوازيلاند","+268","SZ"));
        country.add(new City("جزر الترك وجايكوس","+1","TC"));
        country.add(new City("تشاد","+235","TD"));
        country.add(new City("المقاطعات الجنوبية الفرنسية","+262","TF"));
        country.add(new City("توجو","+228","TG"));
        country.add(new City("تايلند","+66","TH"));
        country.add(new City("طاجكستان","+992","TJ"));
        country.add(new City("توكيلو","+690","TK"));
        country.add(new City("تيمور الشرقية","+670","TL"));
        country.add(new City("تركمانستان","+993","TM"));
        country.add(new City("تونس","+216","TN"));
        country.add(new City("تونجا","+676","TO"));
        country.add(new City("تركيا","+90","TR"));
        country.add(new City("ترينيداد وتوباغو","+1","TT"));
        country.add(new City("توفالو","+688","TV"));
        country.add(new City("تايوان","+886","TW"));
        country.add(new City("تانزانيا","+255","TZ"));
        country.add(new City("أوكرانيا","+380","UA"));
        country.add(new City("أوغندا","+256","UG"));
        country.add(new City("الولايات المتحدة الأمريكية","+1","US"));
        country.add(new City("أورجواي","+598","UY"));
        country.add(new City("أوزبكستان","+998","UZ"));
        country.add(new City("الفاتيكان","+379","VA"));
        country.add(new City("سانت فنسنت وغرنادين","+1","VC"));
        country.add(new City("فنزويلا","+58","VE"));
        country.add(new City("جزر فرجين البريطانية","+1","VG"));
        country.add(new City("جزر فرجين الأمريكية","+1","VI"));
        country.add(new City("فيتنامة","+84","VN"));
        country.add(new City("فانواتو","+678","VU"));
        country.add(new City("جزر والس وفوتونا","+681","VU"));
        country.add(new City("ساموا","+685","WS"));
        country.add(new City("كوسوفو","+383","XK"));
        country.add(new City("اليمن","+967","YE"));
        country.add(new City("مايوت","+262","YT"));
        country.add(new City("جمهورية جنوب افريقيا","+27","YT"));
        country.add(new City("زامبيا","+260","ZM"));
        country.add(new City("زيمبابوي","+263","ZW"));*/

        return country;
    }
}
